apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: graphscope-coordinator
  name: graphscope-coordinator-ide
  namespace: graph-manager
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      graphscope.components: coordinator
      graphscope.coordinator.name: graphscope-coordinator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: coordinator
      labels:
        graphscope.components: coordinator
        graphscope.coordinator.name: graphscope-coordinator
    spec:
      containers:
      - command:
        - python3
        - -m
        - gscoordinator
        - --cluster_type
        - k8s
        - --port
        - "59001"
        - --num_workers
        - "2"
        - --instance_id
        - graphscope
        - --log_level
        - INFO
        - --k8s_namespace
        - default
        - --k8s_service_type
        - NodePort
        - --preemptive
        - "true"
        - --k8s_gs_image
        - registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.9.1
        - --k8s_etcd_image
        - quay.io/coreos/etcd:v3.4.13
        - --k8s_image_pull_policy
        - Always
        - --k8s_image_pull_secrets
        - ''''''
        - --k8s_coordinator_name
        - graphscope-coordinator
        - --k8s_coordinator_service_name
        - graphscope-coordinator-service
        - --k8s_etcd_cpu
        - "0.5"
        - --k8s_etcd_mem
        - 128Mi
        - --k8s_vineyard_daemonset
        - '""'
        - --k8s_vineyard_cpu
        - "0.5"
        - --k8s_vineyard_mem
        - 512Mi
        - --vineyard_shared_mem
        - 4Gi
        - --k8s_engine_cpu
        - "0.5"
        - --k8s_engine_mem
        - 4Gi
        - --k8s_volumes
        - '{}'
        - --timeout_seconds
        - "1200"
        - --dangling_timeout_seconds
        - "-1"
        - --waiting_for_delete
        - "False"
        - --k8s_delete_namespace
        - "False"
        env:
        - name: PYTHONUNBUFFERED
          value: "TRUE"
        image: registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.9.1
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - python3
              - /usr/local/bin/pre_stop.py
        name: coordinator
        ports:
        - containerPort: 59001
          name: coordinator
          protocol: TCP
        readinessProbe:
          failureThreshold: 8
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 59001
          timeoutSeconds: 15
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: registry.cn-hongkong.aliyuncs.com/graphscope/jupyter:0.9.1
        imagePullPolicy: Always
        name: jupyter
        ports:
        - containerPort: 8888
          name: jupyter
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30